### ISSUE TITLE
Object Storage Operations Application test is not successful

### ISSUE THREAD

**Issue by mridulrb** [IBM/process-images-derive-insights#8]
I'm facing an issue in the 4th step where we Create object storage operations service. http://localhost:5501/home doesn't display ```Your object storage operations application test is successful```.

<img width="1792" alt="Screen Shot 2020-09-25 at 2 51 10 AM" src="https://user-images.githubusercontent.com/12492961/94208037-f92c2680-fed9-11ea-8350-f82d4ecfce44.png">

**Comment by mridulrb** [comment]
I also keep getting this error - 

(base) Mriduls-MBP-2:object_storage_operations mridulbhandari$ appsody run -p 5501:8080 -p 5502:5678
Running development environment...
Using local cache for image dev.local/appsody/python-flask-os:0.2
Running command: docker run --rm -p 5501:8080 -p 5502:5678 --name object-storage-operations -v /Users/mridulbhandari/Documents/GitHubPersonal/process-images-derive-insights/object_storage_operations/:/project/userapp -v appsody-object-storage-operations-20200925230957.64315100:/project/deps -v appsody-controller-0.3.5:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/python-flask-os:0.2 "--mode=run"
[Container] Running APPSODY_PREP command: cd /project/userapp;pipenv lock -r > ../requirements-additional.txt;python -m pip install -r ../requirements-additional.txt -t /project/deps
[Container] Creating a virtualenv for this project…
[Container] Pipfile: /project/userapp/Pipfile
[Container] Using /usr/local/bin/python3.7m (3.7.9) to create virtualenv…
⠼ Creating virtual environment...created virtual environment CPython3.7.9.final.0-64 in 781ms
[Container]   creator CPython3Posix(dest=/home/worker/.local/share/virtualenvs/userapp-pHZHaS8v, clear=False, global=False)
[Container]   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/worker/.local/share/virtualenv)
[Container]     added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
[Container]   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[Container]
:heavy_check_mark: Successfully created virtual environment!
[Container] Traceback (most recent call last):
[Container]   File "/home/worker/.local/bin/pipenv", line 8, in <module>
[Container]     sys.exit(cli())
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
[Container]     return self.main(*args, **kwargs)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 782, in main
[Container]     rv = self.invoke(ctx)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
[Container]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
[Container]     return ctx.invoke(self.callback, **ctx.params)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
[Container]     return callback(*args, **kwargs)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
[Container]     return ctx.invoke(f, obj, *args, **kwargs)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
[Container]     return callback(*args, **kwargs)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
[Container]     return f(get_current_context(), *args, **kwargs)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/cli/command.py", line 335, in lock
[Container]     warn=(not state.quiet), site_packages=state.site_packages,
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/core.py", line 580, in ensure_project
[Container]     pypi_mirror=pypi_mirror,
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/core.py", line 512, in ensure_virtualenv
[Container]     python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/core.py", line 999, in do_create_virtualenv
[Container]     project._environment.add_dist("pipenv")
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/environment.py", line 135, in add_dist
[Container]     self.extend_dists(dist)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/environment.py", line 127, in extend_dists
[Container]     extras = self.resolve_dist(dist, self.base_working_set)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/environment.py", line 122, in resolve_dist
[Container]     deps |= cls.resolve_dist(dist, working_set)
[Container]   File "/home/worker/.local/lib/python3.7/site-packages/pipenv/environment.py", line 121, in resolve_dist
[Container]     dist = working_set.find(req)
[Container]   File "/project/deps/pkg_resources/__init__.py", line 627, in find
[Container]     raise VersionConflict(dist, req)
[Container] pkg_resources.VersionConflict: (importlib-metadata 2.0.0 (/project/deps), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))
[Container] Running command:  python -m flask run --host=0.0.0.0 --port=8080
[Container]  * Serving Flask app "/project/server/__init__.py"
[Container]  * Environment: production
[Container]    WARNING: This is a development server. Do not use it in a production deployment.
[Container]    Use a production WSGI server instead.
[Container]  * Debug mode: off
[Container] Usage: python -m flask run [OPTIONS]
[Container]
[Container] Error: While importing "server", an ImportError was raised:
[Container]
[Container] Traceback (most recent call last):
[Container]   File "/project/deps/flask/cli.py", line 240, in locate_app
[Container]     __import__(module_name)
[Container]   File "/project/server/__init__.py", line 5, in <module>
[Container]     from userapp import *
[Container]   File "/project/userapp/__init__.py", line 2, in <module>
[Container]     import requests
[Container] ModuleNotFoundError: No module named 'requests'
[Container]
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST exit status 2
